a--
ORG 1000h
EOI EQU 20H
IMR EQU 21H
INT1 EQU 25H

CONT EQU 10H
COMP EQU 11H
ORG 40
DIR_MOSTRAR DW 3000H
ORG 1200H
STRING DB "VAMOS LAS INTERRUPCIONES"
SALTO DB 10
FIN DB ?
ORG 3000H
MOSTRAR: MOV BX, OFFSET STRING
         MOV AL, OFFSET FIN - OFFSET STRING
         INT 7
         
         MOV AL,0
         OUT CONT, AL; REINICIO TIMER
         MOV AL, 20H
         OUT EOI, AL
         
         IRET

ORG 2000H
CLI
MOV AL, 0FDH ; DEFINO IMR
OUT IMR, AL

MOV AL, 10
OUT INT1, AL; DEFINO VALOR DENTRO DE PIC

MOV AL, 0 
OUT CONT, AL

MOV AL, 2
OUT COMP, AL; DEFINO COMP
STI
LAZO: JMP LAZO
INT 0
END

b---
ORG 1000h
EOI EQU 20H
IMR EQU 21H
INT1 EQU 25H

CONT EQU 10H
COMP EQU 11H
ORG 40
DIR_MOSTRAR DW 3000H
ORG 1200H
STRING DB "VAMOS LAS INTERRUPCIONES"
SALTO DB 10
FIN DB ?
ORG 3000H
MOSTRAR: ADD AH, 2
         MOV BX, OFFSET STRING
         MOV AL, OFFSET FIN - OFFSET STRING
         INT 7
         
         MOV AL,0
         OUT CONT, AL; REINICIO TIMER
 DETENERI:MOV AL, 20H
         OUT EOI, AL
         
         IRET

ORG 2000H
MOV AX,0
CLI
MOV AL, 0FDH ; DEFINO IMR
OUT IMR, AL

MOV AL, 10
OUT INT1, AL; DEFINO VALOR DENTRO DE PIC

MOV AL, 2
OUT COMP, AL; DEFINO COMP
MOV AL, 0 
OUT CONT, AL
STI
LAZO: CMP AH, 10
JNZ LAZO
INT 0
END

C--
ORG 1000h
EOI EQU 20H
IMR EQU 21H
INT1 EQU 25H

CONT EQU 10H
COMP EQU 11H
ORG 40
DIR_MOSTRAR DW 3000H
ORG 1200H
STRING DB "VAMOS LAS INTERRUPCIONES"
SALTO DB 10
FIN DB ?
FLAG DB ?
ORG 3000H
MOSTRAR: MOV BX, OFFSET STRING
         MOV AL, OFFSET FIN - OFFSET STRING
         INT 7
         
         MOV FLAG, 1
 DETENERI:MOV AL, 20H
         OUT EOI, AL
         IRET

ORG 2000H
MOV AX,0
CLI
MOV AL, 0FDH ; DEFINO IMR
OUT IMR, AL

MOV AL, 10
OUT INT1, AL; DEFINO VALOR DENTRO DE PIC

MOV AL, 10
OUT COMP, AL; DEFINO COMP
MOV AL, 0 
OUT CONT, AL
STI
LAZO: CMP FLAG,1
JNZ LAZO
INT 0
END

D----
ORG 1000h
EOI EQU 20H
IMR EQU 21H
INT1 EQU 25H

CONT EQU 10H
COMP EQU 11H
ORG 40
DIR_MOSTRAR DW 3000H
ORG 1200H
STRING DB "VAMOS LAS INTERRUPCIONES"
SALTO DB 10
FIN DB ?
FLAG DB ?
ORG 3000H
MOSTRAR: MOV BX, OFFSET STRING
         MOV AL, OFFSET FIN - OFFSET STRING
         INT 7
         IN AL, CONT
         CMP AL, 0FFH
         JZ LLEGUE
         INC AL
         OUT COMP, AL
         JMP DETENERI
  LLEGUE: MOV FLAG, 1
 DETENERI: MOV AL, 0
         OUT CONT, AL
         MOV AL, 20H
         OUT EOI, AL
         IRET

ORG 2000H
MOV AX,0
CLI
MOV AL, 0FDH ; DEFINO IMR
OUT IMR, AL

MOV AL, 10
OUT INT1, AL; DEFINO VALOR DENTRO DE PIC

MOV AL, 1
OUT COMP, AL; DEFINO COMP
MOV AL, 0 
OUT CONT, AL; DEFINO CONT 0
STI
LAZO: CMP FLAG,1
JNZ LAZO
INT 0
END
