ORG 1000H
EOI EQU 20H
IMR EQU 21H
INT2 EQU 26H

HAND_DATA EQU 40H
HAND_STATUS EQU 41H
ORG 48
DW ENVIAR

ORG 1500H
STRING DB "UNIVERSIDAD NACIONAL DE LA PLATA"
FIN DB ?
ORG 3000H
ENVIAR: PUSH AX
        MOV AL, [BX]; LE MANDO EL ELEM
        OUT HAND_DATA, AL
        INC BX
I_STOP: MOV AL, 20H
        OUT EOI, AL
        POP AX
        IRET
        
ORG 2000H
; CONFIGURO PIC
CLI
MOV AL, 11111011B
OUT IMR, AL

MOV AL, 12
OUT INT2, AL; INSTRUCCION PARA LA INT EN PIC
STI
MOV BX, OFFSET STRING
; CONFIGURAR HANDSHAKE
IN AL, HAND_STATUS
OR AL, 10000000B
OUT HAND_STATUS, AL; LE CONFIGURO EL BIT 7 PARA QUE ADMITA INTS
LAZO: CMP BX, OFFSET FIN
JNZ LAZO
; CONFIGURAR SALIDA HANDSHAKE
IN AL, HAND_STATUS
AND AL, 0111111B
OUT HAND_STATUS, AL
INT 0
END

C---
ORG 1000H
EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H
INT2 EQU 26H

HAND_DATA EQU 40H
HAND_STATUS EQU 41H
ORG 48
DW ENVIAR
ORG 52
DW DETENER
ORG 1500H
STRING DB "UNIVERSIDAD NACIONAL DE LA PLATA"
FIN DB ?
ORG 3000H
ENVIAR: PUSH AX
        MOV AL, [BX]; LE MANDO EL ELEM
        OUT HAND_DATA, AL
        INC BX

I_STOP: MOV AL, 20H
        OUT EOI, AL
        POP AX
        IRET
        
DETENER: PUSH AX
          MOV BX, OFFSET FIN
          IN AL, HAND_STATUS
          AND AL, 0111111B
          OUT HAND_STATUS, AL
          JMP I_STOP
          
ORG 2000H
; CONFIGURO PIC
CLI
MOV AL, 11111010B
OUT IMR, AL

MOV AL, 12
OUT INT2, AL; INSTRUCCION PARA LA INT EN PIC
MOV AL, 13
OUT INT0, AL
STI
MOV BX, OFFSET STRING
; CONFIGURAR HANDSHAKE
IN AL, HAND_STATUS
OR AL, 10000000B
OUT HAND_STATUS, AL; LE CONFIGURO EL BIT 7 PARA QUE ADMITA INTS
LAZO: CMP BX, OFFSET FIN
JNZ LAZO
; CONFIGURAR SALIDA HANDSHAKE
IN AL, HAND_STATUS
AND AL, 0111111B
OUT HAND_STATUS, AL
INT 0
END
