#include <stdio.h>
#include <stdlib.h>

int main()
{
   /*

   STRUCT PERSONA EN EL PRIMER CASO PUEDE DEFINIR LA PERSONA Y UNA VARIABLE, LUEGO REDEFINE STRUCT PERSONA COMO PERSONAT PARA LA SECCION DONDE FUE CREADA.
   TYPEDEF STRUCT PERSONA DEFINE LA MISMA ESTRUCTURA Y LA REDEFINE POR LO QUE ESTA DETRAS DEL CORCHETE, PERO NO PUEDE CREAR UNA VARIABLE DESPUES
   */
    return 0;
}
