// RESTO + DIV POR PILA REG + MUL PILA REG
ORG 1000H
NUM1 DB 15;DIVIDENDO
NUM2 DB 2; DIVISOR
RES DB 0
ORG 3000H
DIV:PUSH BX; div a y b se pasan por valor por pila y por ahi
MOV BX, SP
ADD BX, 4
PUSH AX
PUSH CX
MOV CX, 0
MOV AX, [BX]
ADD BX, 2
CMP AL, 0
JZ FIN
CMP AH,0 
JZ FIN
RESTAR: CMP AL,AH
JS FIN
SUB AL,AH
INC CL
JMP RESTAR
FIN: MOV [BX],CL 
POP CX
POP AX
POP BX
RET

MUL: PUSH BX
MOV BX, SP
ADD BX, 4
PUSH AX
MOV AX, [BX]
VERIF: CMP AL,0
JZ FIN_MUL
CMP AH,0
JZ FIN_MUL
MOV CX,0
LOOP: ADD CL, AH
DEC AL
JNZ LOOP
FIN_MUL: POP AX
POP BX
RET;
;RECIBO POR VALOR
RESTO: PUSH BX; DEV REF REG
PUSH AX; DATOS
PUSH CX; DEVUELVE RESULTADO DE LA DIVISION
; REUTILIZACION
PUSH CX
PUSH AX
CALL DIV
POP AX
POP CX; DEVOLUCION DE DIV POR CL
;UTILIZO ESE DIV PARA MUL
MOV CH, AH; PARA TENER AMBOS DATOS EN UN REGISTRO Y ENVIARLO EN PILA
PUSH CX; EN EL MISMO REG CL = DATO A CH = DATO B
CALL MUL
MOV AH, CL; REEMPLAZA B POR EL VALOR DEVUELTO
POP CX
SUB AL, AH; A-(A DIV B) MUL B
MOV [BX], AL; DEVUELVE REG POR REFERENCIA BX
POP CX
POP AX
POP BX
RET

ORG 2000H
MOV AL, NUM1
MOV AH, NUM2
MOV BX, OFFSET RES
CALL RESTO
HLT 
END

