ORG 1000H
TABLAA DB "**MI_cONTraSEñA.UnICa"; REF PILA
VOCALS DB "AEIOU" 
RESULT DB 0
; PRIMERO, LEO EL CARACTER SI ES MAYUSCULA VOCAL
ORG 3000H

ES_VOCAL: PUSH BX; BX TIENE LA DIR DE VOCALES
PUSH AX; AX TENDRÁ EL OFFSET DEL CHAR , NO PUSHEO CX PORQUE CL TIENE LA DIML DE VOCALES Y CH ES EL DATO A EVALUAR
PUSH BX
MOV BX, AX
MOV AX,0
MOV AL, [BX]
POP BX; CON ESTO HAGO QUE AL, TENGA EL VALOR DE A
; ME DEVOLVÍ EL DATO
BUCLE: CMP AL, [BX]
JZ SI_ES_VOCAL
INC BX
DEC CL
JNZ BUCLE
NO_ES_VOCAL: MOV CH, 00H
JMP FIN_ES_VOCAL
SI_ES_VOCAL: MOV CH, 0FFH
FIN_ES_VOCAL: POP AX
POP BX
RET

ENCRYPT: PUSH BX
MOV BX,SP
ADD BX,4
PUSH DX; USARÉ DL COMO UN AUXILIAR DE LOS PARAMETROS PARA PODER ASIGNARSELOS A [BX]
MOV BX, [BX]; TENGO EL OFFSET DE A
CASE1: CMP BYTE PTR[BX], 41H ; SI ES A ENTONCES
JNZ CASE2
MOV DL, 40H
JMP CHANGE
CASE2: CMP BYTE PTR[BX], 45H
JNZ CASE3
MOV DL, 45H
JMP CHANGE
CASE3: CMP BYTE PTR[BX], 49H
JNZ CASE4
MOV DL, 21H
JMP CHANGE
CASE4: CMP BYTE PTR[BX], 4FH
JNZ CASE5
MOV DL,30H
JMP CHANGE
CASE5: CMP BYTE PTR[BX], 55H
JNZ BREAK;
MOV DL, 75H
CHANGE: MOV [BX],DL
BREAK: POP DX
POP BX
RET


ORG 2000H
MOV AX, OFFSET TABLAA; TENGO LAS VOCALES
MOV DL, 0; SERÁ EL CONTADOR DE LAS MODIFICACIONES{
MOV DH, OFFSET VOCALS- OFFSET TABLAA; DIML DE LA TABLA DE CARACTERES
RESTABLECER: MOV CL, OFFSET RESULT- OFFSET VOCALS; DIML DE VOCALES 
MOV CH,0
MOV BX, OFFSET VOCALS
HACER:CALL ES_VOCAL
CMP CH, 0FFH
JNZ SIGUIENTE
PUSH AX
CALL ENCRYPT; SI ENTRÓ ACA SIGNIFICA QUE ES UNA VOCAL POR LO TANTO, CAMBIARÁ
POP AX; HAGO POP ACÁ YA QUE NO LO NECESITO PARA INCREMENTAR GRACIAS A MI ETIQUETA SIGUIENTE
INC DL
SIGUIENTE: INC AX; PASO AL SIGUIENTE DATO DE LA CADENA
DEC DH
JNZ RESTABLECER
FINAL: MOV RESULT, DL
HLT
END