ORG 1000H
PRINT EQU 40H
POLL EQU 41H
STR DB "INGENIERIA INFORMATICA"
FIN DB ?
;00000000
ORG 2000H 
MOV BX, OFFSET STR
MOV CL,  OFFSET FIN - OFFSET STR
POLLING: IN AL, POLL
         AND AL, 1; ME DEVUELVE 0000000B
         JNZ POLLING
         MOV AL, [BX]
         OUT PRINT, AL
         INC BX
         DEC CL
         JNZ POLLING; 
int 0
end
