a---
ORG 2000H
; PA, CA LLAVE
; PB, BC LUCES
; IN AL, 40H LEER DATO QUE ESTA EN MEM E/S
; OUT 40H, AL ESCRIBIR EN MEMORIA E/S EL DATO DE AL 
MOV AL, 11111111B; configuracion si hubiera usado llave y luces
OUT 32H, AL; TODAS DE ENTRADA
; lo que pide
not AL
OUT 33H, AL
MOV AL, 11000011b
LOOP:OUT 31H, AL
JMP LOOP
INT 0
END

B----
ORG 1000H
PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H
STRING DB "LLAVE " 
SBTRING1 DB "PRENDIDA"
SBTRING2 DB "APAGADA"
FIN DB ?
ORG 2000H
; PA, CA LLAVE
; PB, BC LUCES
; IN AL, 40H LEER DATO QUE ESTA EN MEM E/S
; OUT 40H, AL ESCRIBIR EN MEMORIA E/S EL DATO DE AL 
MOV AL, 11111111B
OUT CA, AL
MOV BX, OFFSET STRING
IN AL, PA
CMP AL, 10000000B
JS APAGADA
PRENDIDA: MOV AL, OFFSET SBTRING2 - OFFSET STRING
INT 7 
JMP FINAL
APAGADA: MOV AL, OFFSET SBTRING1 - OFFSET STRING
INT 7
MOV BX, OFFSET SBTRING2
MOV AL, OFFSET FIN - OFFSET SBTRING2
INT 7
FINAL:int 0
end
