ORG 1000H
PA EQU 30H; SB 
PB EQU 31H; DATOS
CA EQU 32H; XXXXX01 , SALIDA ENTRADA
CB EQU 33H; SALIDA


POLL EQU 41H
STR DB "ORGANIZACION DE COMPUTADORAS"
FIN DB ?
;00000000
ORG 3000H
; CONFIGURO CA
CONF_PIO: MOV AL, 01H
OUT CA, AL
; CONFIGURA CB
MOV AL, 0
OUT CB, AL
RET; ESTO SETEA LOS VALORES DE CONFIGURACION
; 1 VEZ X EJECUCION
STROBE0: IN AL, PA
AND AL, 0FDH
OUT PA, AL
RET
STROBE1: IN AL, PA
OR AL, 2
OUT PA, AL
RET

ORG 2000H
MOV BX, OFFSET STR
MOV CL, OFFSET FIN- OFFSET STR
CALL CONF_PIO
POLLING: IN AL,PA
        AND AL, 1 ; SI BUSY 1 ESPERAR, SINO SIGO
        JNZ POLLING 
MOV AL, [BX]
OUT PB, AL
CALL STROBE0; REPASAR TEORIA DEL STROBE O A 1
CALL STROBE1
INC BX
DEC CL
JNZ POLLING
int 0
end

;C
;--
ORG 1000H
PA EQU 30H; SB 
PB EQU 31H; DATOS
CA EQU 32H; XXXXX01 , SALIDA ENTRADA
CB EQU 33H; SALIDA


POLL EQU 41H
STR DB "PICHI TE AMO <3 "

ORG 1200H
PANTALLA DB "INGRESE 5 ELEMENTOS"
FINPANTALLA DB ?
SALTO DB 10H
;00000000
ORG 3000H
; CONFIGURO CA
CONF_PIO: MOV AL, 01H
OUT CA, AL
; CONFIGURA CB
MOV AL, 0
OUT CB, AL
RET; ESTO SETEA LOS VALORES DE CONFIGURACION
; 1 VEZ X EJECUCION
STROBE0: IN AL, PA
AND AL, 0FDH
OUT PA, AL
RET
STROBE1: IN AL, PA
OR AL, 2
OUT PA, AL
RET
MOSTRAR_STR: PUSH BX
            PUSH AX
            MOV AL, OFFSET FINPANTALLA - OFFSET PANTALLA
            INT 7
            CALL SALTO_LINEA
            POP AX
            POP BX
            RET

SALTO_LINEA: PUSH BX
            PUSH AX
            MOV BX, OFFSET SALTO
            MOV AL, 1
            INT 7
FIN_SALTO_LINEA: POP AX 
            POP BX
            RET

ORG 2000H

MOV BX, OFFSET PANTALLA
MOV CL, 5
CALL CONF_PIO
CALL MOSTRAR_STR
MOV BX, OFFSET STR
POLLING: IN AL,PA
        AND AL, 1 ; SI BUSY 1 ESPERAR, SINO SIGO
        JNZ POLLING 
INT 6
MOV AL, [BX]
OUT PB, AL
CALL STROBE0; REPASAR TEORIA DEL STROBE O A 1
CALL STROBE1
INC BX
DEC CL
JNZ POLLING
int 0
end
