ORG 1000H
TABLAA DW 5,3,4,6,2; REF VIA PILA
TABLAB DW 0,2,4,3,4; VALOR VIA PILA
CONT DB 0; SI A MAYOR A B , REEMPLAZAR B EN A

ORG 3000H
SUBRUTINA: PUSH BX
MOV BX, SP
ADD BX, 4
PUSH AX
MOV AX,[BX]; LE PASA EL DATO B
ADD BX, 2
MOV BX, [BX]; TIENE EL OFFSET A
HACER: CMP AX, [BX]
JNS FIN_SUB
SWITCH: MOV [BX], AX
FIN_SUB: POP AX
POP BX
RET

ORG 2000H
MOV BX, OFFSET TABLAA
MOV CL, OFFSET TABLAB - OFFSET TABLAA; 10 PONELE
MOV CH, Cl; CONTADOR DEL FOR 
MOV DX,0
SETTER:PUSH BX
ADD BL, CL
MOV AX, [BX]
POP BX
DOING:PUSH BX
PUSH AX
CALL SUBRUTINA
POP AX
POP BX
CMP AX,10
JNZ SIGO
INC DL
SIGO:ADD BX,2
SUB CH,2
JNZ SETTER
MOV CONT, DL
HLT
END