ORG 1000H
C DB "e4stE&3s.el.r3çup3R@t0r1o!"; REF PILA HAY QUE RESTARLE 20
CONT DB 0
ORG 3000H
MAYUS: PUSH BX
MOV BX, SP
ADD BX ,4
PUSH AX
MOV AX,0
MOV BX, [BX];OFFSET C
MOV AL, [BX]
IF: CMP AL, 61H;
JS FIN_SUB
CMP AL, 7BH; DE ESA FORMA INCLUTO 7AH
JNS FIN_SUB 
THEN: SUB AL, 20H
MOV [BX], AL
FIN_SUB: POP AX
POP BX
RET

ORG 2000H
MOV BX,  OFFSET C
MOV AL, OFFSET CONT - OFFSET C
MOV AH, 0; CONT
BUCLE: PUSH BX
CALL MAYUS
MOV BL, [BX]
CMP BL, 45H
JNZ SIGO
INC AH
SIGO: POP BX
INC BX
DEC AL
JNZ BUCLE
MOV CONT, AH
HLT
END