ORG 1000H
EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H; F10
INT1 EQU 25H; TIMER
INT2 EQU 26H; HANDSHAKE

PA EQU 30H; LLAVES
PB EQU 31H; LEDS
CA EQU 32H
CB EQU 33H
; PA, CA LLAVE
; PB, BC LUCES
; IN AL, 40H LEER DATO QUE ESTA EN MEM E/S
; OUT 40H, AL ESCRIBIR EN MEMORIA E/S EL DATO DE AL 
HAND_DATA EQU 40H
HAND_STATUS EQU 41H
FLAG DB 0
NUM DB ?
ORG 40
DW RULETA

ORG 3000H
RULETA: MOV BYTE PTR[BX], AL; ASEGURO EL DATO POR SI LA INT SE INVOCÓ EN MEDIO DEL LAZO
MOV FLAG, 1; SUPONIENDO LEDS DE SALIDA
  I_STOP:   PUSH AX
            MOV AL, 20H
            OUT EOI, AL
            POP AX
            IRET
ORG 2000H
CLI
MOV AL, 11111110B; HABILITO INTERRUPCION INT0
OUT IMR, AL

MOV AL, 10
OUT INT0, AL; LE DOY A INT0 UN ID PARA EL VECTOR DE INTERRUPCION

STI
MOV BX, OFFSET NUM
MOV AL,30H 
LAZO: CMP FLAG,1
JZ FIN
INC AL
CMP AL, 39H
JNZ LAZO
MOV AL, 30H
JMP LAZO
FIN: MOV AL, FLAG
INT 7
INT 0
END
