ORG 1000H
EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H; F10
INT1 EQU 25H; TIMER
INT2 EQU 26H; HANDSHAKE

PA EQU 30H; LLAVES
PB EQU 31H; LEDS
CA EQU 32H
CB EQU 33H
; PA, CA LLAVE
; PB, BC LUCES
; IN AL, 40H LEER DATO QUE ESTA EN MEM E/S
; OUT 40H, AL ESCRIBIR EN MEMORIA E/S EL DATO DE AL 
HAND_DATA EQU 40H
HAND_STATUS EQU 41H
FLAG DB 0
STRING DB "F10 PARA START!"
STRING2 DB "ESCRIBA UN MENSAJE DE 10 CARACTERES"
PRECADENA DB ?
CADENA DB ?,?,?,?,?,?,?,?,?,?
FINCADENA DB ?
ORG 40
DW START

ORG 3000H
START: PUSH BX; BX OFFSET DE CADENA
       PUSH BX
         MOV BX, OFFSET STRING2
         MOV AL, OFFSET CADENA - OFFSET STRING2
         INT 7
       POP BX
       MOV AL, OFFSET FINCADENA - OFFSET CADENA
  LECTURA:  INT 6
            INC BX
            DEC AL
            JNZ LECTURA
            DEC BX; ESTO ME DEJA EN EL ULTIMO ELEMENTO DEL VECTOR
            CALL APILAR_IMPRESORA
            POP BX  
  I_STOP:   PUSH AX
            MOV AL, 20H
            OUT EOI, AL
            POP AX
            IRET
APILAR_IMPRESORA: MOV AH, BYTE PTR[BX] ; PILA TIENE ESTRUCTURA LIFO, LAST IN FIRST OUT
            DEC BX
            MOV AL, BYTE PTR[BX]
            DEC BX
            PUSH AX; MANDO A PILA LOS CARACTERES
            CMP BX, OFFSET PRECADENA
            JNZ APILAR_IMPRESORA
IMPRIMIR: MOV DL, 5; 5 VUELTAS
POLLING:  IN AL, PA
          AND AL, 1; SI BUSY EN 1 ESTA OCUPADO 
          JNZ POLLING
          POP CX; DEBO HACER 5 POPS
LETRA_L:  MOV AL, CL
          OUT PB, AL
          CALL STROBE0
          CALL STROBE1
POLLING2:  IN AL, PA
          AND AL, 1; SI BUSY EN 1 ESTA OCUPADO 
          JNZ POLLING2
LETRA_H:  MOV AL, CH
          OUT PB, AL
          CALL STROBE0
          CALL STROBE1
          DEC DL
          JNZ POLLING
          MOV FLAG, 1; SIGNIFICA QUE TERMINÓ LA IMPRESION DE DATOS
          RET
          
STROBE0: IN AL, PA
AND AL, 0FDH
OUT PA, AL
RET

STROBE1: IN AL, PA
OR AL, 2
OUT PA, AL
RET

ORG 2000H
CLI
MOV AL, 11111110B; HABILITO INTERRUPCION INT0
OUT IMR, AL

MOV AL, 10
OUT INT0, AL; LE DOY A INT0 UN ID PARA EL VECTOR DE INTERRUPCION

; CONFIGURO PIO PARA LA IMPRESORA

MOV AL, 1; ENTRADA BUSY
OUT CA, AL; 

MOV AL, 0
OUT CB, AL
; PIO CONFIGURADA
 MOV BX, OFFSET STRING
MOV AL, OFFSET STRING2 - OFFSET STRING
INT 7 
MOV BX, OFFSET CADENA 
STI; HABILITO INTERRUPCIONES

LAZO: CMP FLAG,1
JNZ LAZO
FIN: INT 0
END
