ORG 1000H
CONT EQU 10H
COMP EQU 11H

EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H; F10
INT1 EQU 25H; TIMER
INT2 EQU 26H; HANDSHAKE

PA EQU 30H; LLAVES
PB EQU 31H; LEDS
CA EQU 32H
CB EQU 33H
; PA, CA LLAVE
; PB, BC LUCES
; IN AL, 40H LEER DATO QUE ESTA EN MEM E/S
; OUT 40H, AL ESCRIBIR EN MEMORIA E/S EL DATO DE AL 
HAND_DATA EQU 40H
HAND_STATUS EQU 41H

STRING DB "ARQUITECTURA DE COMPUTADORAS: ACTIVADA"
FINSTRING DB ?


ORG 3000H
ESTAN_APAGADAS: IN AL,PA ; DEVUELVE 1 SI ESTAN APAGADAS, 0 SINO
                CMP AL, 0
                JZ SI
            NO: MOV AH, 0
                JMP FIN_ESTAN_APAGADAS
            SI: MOV AH, 1
FIN_ESTAN_APAGADAS: RET

INVERTIR_LUCES: IN AL, PA; 
                NOT AL; INVIERTE LOS VALORES
                OUT PB, AL
                RET
BIT0_ON: PUSH BX
         IN AL, PA
         AND AL, 1
         JZ FIN_BIT0_ON
         MOV BX, OFFSET STRING
         MOV AL, OFFSET FINSTRING - OFFSET STRING
         INT 7       
  FIN_BIT0_ON: POP BX
               RET
         

ORG 2000H
; UTILIZA LLAVES Y LUCES POR LO TANTO CONFIGURO PIO
MOV AL, 0FFH
OUT CA, AL; LLAVES ENTRADA

NOT AL
OUT CB, AL ; LUCES SALIDA
; POR ENUNCIADO SUPONGO QUE LAS LUCES ESTAN CONECTADAS A LAS LLAVES
IN AL, PA
OUT PB, AL; RECIBE LOS VALORES DE LAS LLAVES ENCENDIDAS PARA LAS LUCES
; LISTO CONFIGU PA Y PB
CALL ESTAN_APAGADAS
CMP AH, 1
JZ FIN
CALL INVERTIR_LUCES
CALL BIT0_ON
FIN:INT 0
END
