ORG 1000H
CONT EQU 10H
COMP EQU 11H

EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H; F10
INT1 EQU 25H; TIMER
INT2 EQU 26H; HANDSHAKE

PA EQU 30H; LLAVES
PB EQU 31H; LEDS
CA EQU 32H
CB EQU 33H
; PA, CA LLAVE
; PB, BC LUCES
; IN AL, 40H LEER DATO QUE ESTA EN MEM E/S
; OUT 40H, AL ESCRIBIR EN MEMORIA E/S EL DATO DE AL 
HAND_DATA EQU 40H
HAND_STATUS EQU 41H

STRING DB "INGRESE UN NUMERO DEL 1 AL 9"
STRING2 DB "ERROR! ELIGE UN NUMERO ENTRE 1 Y 9"
FINSTRING2 DB ?
STRING3 DB "TOQUE F10 PARA IMPRIMIR"
NUM DB ?
FLAG DB ?
ORG 40
DW IMPRIMIR

ORG 3000H
LEER_DIGITO: PUSH BX
             PUSH AX
             MOV BX, OFFSET STRING
             MOV AL, OFFSET STRING2 - OFFSET STRING
             INT 7
     LEER:   MOV BX, OFFSET NUM
             INT 6
             CMP BYTE PTR[BX],30H
             JS INCORRECTO
             CMP BYTE PTR[BX], 40H
             JNS INCORRECTO
             JMP FIN_LEER_DIGITO
    INCORRECTO: MOV BX, OFFSET STRING2
                MOV AL, OFFSET FINSTRING2 - OFFSET STRING2
                INT 7 
                JMP LEER
   FIN_LEER_DIGITO: POP AX
                    POP BX
                    RET

DESCENDER: PUSH BX; recibe por pila el valor num
           MOV BX, SP
           ADD BX, 4
           PUSH AX; REUTILIZACION
           MOV AX, [BX]; TENGO VALOR
POLLING: IN AL, HAND_STATUS
         AND AL, 1; PARA VER SI ESTA BUSY
         JNZ POLLING ; SI ME DA 1, SIGNIFICA QUE ESTA OCUPADA, SINO, SIGUE
         MOV AL, AH
         OUT HAND_DATA, AL; ENVIO A LA IMPRESORA EL DATO
         DEC AH
         CMP AH, '0'
         JNS POLLING
FIN_DESCENDER: POP AX
                POP BX
                RET

IMPRIMIR: MOV AH, NUM
          PUSH AX; ENVIO DE PARAMETRO POR VALOR PILA
          CALL DESCENDER
          POP AX
          MOV FLAG,1
  I_STOP: PUSH AX
          MOV AL, 20H
          OUT EOI, AL
          POP AX
          IRET
org 2000h
MOV BX, OFFSET STRING3
; UTILIZARE INT 0 -> F10 POR LO TANTO DEBO CONFIGURAR PIC
CLI
MOV AL, 0FEH
OUT IMR, AL ; HABILITO INTERRUPCION F10 PARA EL IMR

MOV AL, 10 
OUT INT0, AL; ID PARA EL VECTOR DE INTERRUPCION

STI
CALL LEER_DIGITO
MOV AL, OFFSET NUM - OFFSET STRING3
INT 7
LAZO: CMP FLAG,1
JNZ LAZO
FIN:INT 0
END
