A- CALCULA EL FACTORIAL DE 3, USANDO LA PILA COMO RECURSION.
B- EL VALOR FINAL DE CX SERÁ 6.
C- 2 BYTES PARA LA LLAMADA DE RETORNO AL PPAL, OTRA EN LA SUB, OTRA MAS Y  OTRA MAS, HASTA QUE AX DA 0 Y RETORNA LAS DIRECCIONES DE MEMORIA.
D- QUE EL NUMERO NO DEBE REBASAR LOS 16 BITS. CONSULTAR. 